Refactor YAC
hyperledger/iroha pull request #1110
Opened 2021-06-30 06:29 UTC by lebdron

Closes https://github.com/hyperledger/iroha/issues/960

- Prevent infinite vote sending when the round is pruned
- Prevent sending redundant replies with last committed round
- Notify YAC of the latest ledger state to account for asynchronous proposal request
- Notify ordering service clients of packed proposals to prevent delays

2021-06-30 07:37 UTC, kuvaldini commented
Checks are failed

2021-06-30 09:50 UTC, lebdron commented
@kuvaldini That's MSVC, so it is still safe to review the logic :)

2021-07-01 12:21 UTC, kuvaldini approved these changes

2021-07-12 11:03 UTC, kamilsa approved these changes

2021-07-14 09:38 UTC, kamilsa requested changes
Please do not merge until we test it better

2021-07-16 10:16 UTC, kamilsa approved these changes

2021-07-16 10:16 UTC, kuvaldini approved these changes
.

2021-07-19 05:36 UTC, iceseer approved these changes

2021-07-19 06:34 UTC, iceseer requested changes
not to merge yet

2021-07-19 07:56 UTC, iceseer approved these changes

2021-07-19 16:11 UTC, merged