Feature/os cache size limit
hyperledger/iroha pull request #1287
Opened 2021-07-22 07:05 UTC by iceseer

### Description of the Change
Adds Ordering Service cache size limitation.

### Benefits

### Possible Drawbacks

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*

2021-07-22 07:24 UTC, iceseer commented on irohad/ordering/impl/on_demand_ordering_service_impl.cpp
> +
remove plz

2021-07-22 07:24 UTC, iceseer commented on irohad/ordering/impl/on_demand_ordering_service_impl.cpp
> +
remove plz

2021-07-22 07:24 UTC, iceseer commented on irohad/ordering/impl/on_demand_ordering_service_impl.cpp
> +    cached_txs_size_ += boost::size(batch->transactions());
remove plz

2021-07-22 07:27 UTC, kuvaldini commented on irohad/ordering/impl/on_demand_ordering_service_impl.cpp
> +    cached_txs_size_ += boost::size(batch->transactions());
done

2021-07-22 07:46 UTC, kamilsa approved these changes

2021-07-22 08:21 UTC, lebdron commented on irohad/ordering/impl/on_demand_ordering_service_impl.cpp
> +    cached_txs_size_ += boost::size(batch->transactions());
I would suggest to use `ByteSizeLong` on protobuf instead, because transactions can be large which would still cause issues.

2021-07-24 07:56 UTC, kuvaldini approved these changes

2021-07-24 07:56 UTC, kuvaldini requested changes
fix after merge.

2021-08-18 09:57 UTC, closed without merging