Docs: General Metrics
hyperledger/iroha pull request #1299
Opened 2021-07-29 23:12 UTC by LiraLemur

Signed-off-by: Sara <lira.lemur@gmail.com>

### Description of the Change

General information about metrics

### Benefits

Metrics in docs

### Possible Drawbacks

Not very full info. Yet.

2021-07-30 10:23 UTC, kuvaldini commented on docs/source/maintenance/metrics.rst
> +  > curl http://127.0.0.1:8080/metrics
should not be in code block

2021-07-30 10:24 UTC, kuvaldini commented on docs/source/maintenance/metrics.rst
> +  	will give you results like:
Should not be in code-block

2021-07-30 10:25 UTC, kuvaldini commented on docs/source/maintenance/metrics.rst
> +	# HELP blocks_height Total number of blocks in chain
please remove redundant identation.

hint: you can edit it on GitHub with instant preview

2021-07-30 10:25 UTC, kuvaldini requested changes
.

2021-08-04 07:40 UTC, LiraLemur commented on docs/source/concepts_architecture/consensus.rst
> +Important Concepts
Omg, thanks for noticing. Apparently restoring the branch for the review fox somehow added it there with those were unstaged changes. I'll delete it

2021-08-04 20:22 UTC, LiraLemur commented on docs/source/concepts_architecture/consensus.rst
> +Important Concepts
@kuvaldini should be removed now, the rest seems to be fixed based on the correct build.

2021-08-05 09:55 UTC, kuvaldini approved these changes

2021-08-06 14:15 UTC, kamilsa approved these changes

2021-08-10 05:34 UTC, merged