[documentation] #1280: Document Iroha metrics
hyperledger/iroha pull request #2195
Opened 2022-05-11 14:40 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

### Description of the Change

Add documentation for metrics: https://github.com/outoftardis/iroha/blob/doc-metrics/docs/source/guides/metrics.md

### Issue

Closes #1280

2022-05-12 06:40 UTC, appetrosyan requested changes

2022-05-12 06:40 UTC, appetrosyan commented on docs/source/guides/metrics.md
> +To conveniently and thoroughly monitor the performance of the network, you can use metrics: numeric data collected over time about your Iroha network.
```suggestion
To conveniently and thoroughly monitor the performance of the network, we recommend using [prometheus](https://prometheus.io/). It's a program that can monitor your Iroha peer over a separate socket, providing you different kinds of performance metrics. 
```

2022-05-12 06:40 UTC, appetrosyan commented on docs/source/guides/metrics.md
> +You can then analyse the data to make your project even more efficient.
```suggestion
This data can help find performance bottlenecks, and optimise Iroha's configuration. 
```

2022-05-12 06:40 UTC, appetrosyan commented on docs/source/guides/metrics.md
> +To use metrics, you need to add it to your [Iroha configuration](../references/config.md).
```suggestion
To use metrics, you need to configure a metrics endpoint in the [Iroha configuration](../references/config.md). By default the endpoint is exposed at `127.0.0.1:8180/metrics`, if the port is not available, Iroha will still start and work normally, but metrics won't be accessible.
```

2022-05-12 06:41 UTC, appetrosyan commented
I think we need a little more detail on what metrics are gathered exactly. Perhaps we should add a subcommand to `kagami` to generate a `metrics` reference, what do you think @Arjentix ?

2022-05-12 21:46 UTC, Arjentix commented
Still there is no way to read about all metrcis without requesting an end-point. So this PR doesn't close the issue, but maybe it shouldn't...

@appetrosyan , I don't know how exactly prometheus metrics are working in our project, but if it's possible to generate this reference, it would be very good.

After looking at code I think it might be possible with procedural macro and global variable magic. We can try it

2022-05-12 21:50 UTC, Arjentix approved these changes
I think the doc is alright and we can merge it now and update later, then there will be a reference generated by our `kagami` tool

2022-05-16 08:01 UTC, appetrosyan approved these changes

2022-05-18 08:01 UTC, Arjentix approved these changes

2022-05-18 08:53 UTC, merged