[enhancement] #2257 : Revoke should emit RoleRevoked
hyperledger/iroha pull request #2264
Opened 2022-05-25 16:10 UTC by omkar-mohanty

### Description of the Change
This PR makes `Revoke` role emit `RoleRevoked` instead of `Permission` event. 
### Issue
`Revoke` role emits `Permission` events which is a misleading since roles are a collection of permission events.
### Benefits
More accurate information about the user.
### Possible Drawbacks
Not sure about drawbacks because I am new to the codebase.

2022-05-27 15:42 UTC, omkar-mohanty commented
I stumbled upon `impl<W: WorldTrait> Execute<W> for Unregister<Role>` which emits a `PermissionRemoved` event should I change that to `RoleRevoked` event?

2022-05-27 15:55 UTC, omkar-mohanty commented
@appetrosyan This PR is ready for review

2022-05-27 16:01 UTC, appetrosyan submitted a review, later dismissed

2022-05-27 16:10 UTC, omkar-mohanty commented
Hello maintainers I have addressed the issue in #2257 which was originally from #2007 by adding `RoleRevoked` event implementation. This PR still does not implement proper event processing for `RoleRevoked` as noted by @appetrosyan but I would like to have this PR merged as it is. Thanks for reviewing my code.

2022-05-27 16:11 UTC, omkar-mohanty commented
For the event processing issue I have created #2280

2022-05-30 04:40 UTC, s8sato requested changes
For symmetry we also need something like `RoleGranted` for `PermissionAdded`

2022-05-30 11:37 UTC, outoftardis commented on data_model/src/events/data/filters.rs
>          /// Filter by MetadataRemoved event
```suggestion
        ByPermissionAdded,
        /// Filter by `PermissionRemoved` event
        ByPermissionRemoved,
        /// Filter by `RoleRevoked` event
        ByRoleRevoked,
        /// Filter by `RoleGranted` event
        ByRoleGranted,
        /// Filter by `MetadataInserted` event
        ByMetadataInserted,
        /// Filter by `MetadataRemoved` event
```

plus the same change for the lines above these

2022-05-31 06:28 UTC, appetrosyan approved these changes

2022-05-31 06:29 UTC, merged