[enhancement] #2276: Include current Block hash into BlockHeaderValue
hyperledger/iroha pull request #2285
Opened 2022-05-28 16:06 UTC by omkar-mohanty

### Description of the Change
This PR introduces `current_block_hash` field to `BlockHeaderValue`. This field contains the hash of the latest `VersionComittedBlock`. 
### Issue
When we query for block headers we cannot reliably compute the hash of the block, since it's computed from the byte representation of the block and can be architecture dependent.
### Benefits
The Hash of a block will no longer be architecture dependent. 
### Possible Drawbacks
Not that I know of.

2022-05-29 11:19 UTC, appetrosyan requested changes

2022-05-29 11:19 UTC, appetrosyan commented on core/src/block.rs
> +        } = self.clone().into_v1();
This clone is copying a lot of data. I would prefer if you cloned the only moved value instead.

2022-05-29 11:19 UTC, appetrosyan commented
Please observe that the expression `enhancement` is not one of the approved titles for feature-implementations, and amend both the commit message and the title of the PR.

2022-06-01 07:03 UTC, appetrosyan approved these changes

2022-06-04 07:17 UTC, appetrosyan approved these changes

2022-06-04 13:56 UTC, Arjentix approved these changes

2022-06-04 14:39 UTC, Arjentix approved these changes

2022-06-07 06:22 UTC, appetrosyan approved these changes

2022-06-07 06:22 UTC, merged