[feature] #2228: Add Unauthorized variant to smartcontracts query error
hyperledger/iroha pull request #2428
Opened 2022-07-01 16:12 UTC by ales-tsurko

Closes #2228

### Description of the Change

Added `iroha_core::smartcontracts::query::Error::Unauthorized` to better mirror semantics of unauthorized request (i.e. without an account in this case). Also, in case of querying without an account, **HTTP 401 UNAUTHORIZED** status is returned.

### Issue

Previously, in case of query without an account `FindError::Account` returned. And the corresponding **HTTP 404 NOT_FOUND** status code returned. That appeared to be semantically incorrect.

### Benefits

Now `POST /query` in case of request without an account returns `Error::Unauthorized` and **HTTP 401 UNAUTHORIZED** status code.

### Alternate Designs *[optional]*

At first glance, this can be moved to `Error::Permission` and the `Unauthorized` variant could be added to `DenialReason`, but it doesn't share semantics with **HTTP 401 UNAUTHORIZED** (it's **HTTP 403 FORBIDDEN** instead, [which is different](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)).

2022-07-04 06:08 UTC, appetrosyan submitted a review, later dismissed
After merge add it to #api_changes

2022-07-04 06:24 UTC, Erigara commented on core/src/wsv.rs
> +        // .map_err(Into::into)
commented code

2022-07-04 06:25 UTC, Erigara requested changes
Will approve after removing commented code

2022-07-04 23:51 UTC, pesterev commented on core/src/wsv.rs
> +        let account = domain.account(id).ok_or(QueryError::Unauthorized)?;
it looks strange to me that not being able to find the account means the account is not authorized.

2022-07-05 00:11 UTC, pesterev reviewed
LGTM but left comment that suggests one minor improvement

2022-07-05 00:11 UTC, pesterev commented on core/src/smartcontracts/isi/account.rs
> +                    }
```suggestion
                    QueryError::Find(find_err) if matches!(*find_err, FindError::Asset(_)) => {
                        assert_can_register(&asset_id.definition_id, wsv, self.object.value())?;
                        wsv.asset_or_insert(asset_id, self.object.value().clone())
                            .expect("Account exists");
                        Ok(())
                    }
```

2022-07-05 14:29 UTC, Erigara approved these changes

2022-07-05 14:29 UTC, merged