[documentation] Fix #2957, update the MAINTAINERS.md file
hyperledger/iroha pull request #2958
Opened 2022-11-21 07:24 UTC by 6r1d

This PR contains a new maintainer list, feel free to point out who should be added or removed.

2022-11-21 07:59 UTC, outoftardis commented on MAINTAINERS.md
line 4: "by explain" -> "by explaining"

2022-11-21 07:59 UTC, outoftardis commented on MAINTAINERS.md
> +| Bogdan Mingela        | [@Mingela](https://github.com/Mingela)               | mingela@soramitsu.co.jp         | Tribe Lead                                                                    |
I don't think people outside the company know what we mean by tribe so it's better to have a different description here

2022-11-21 07:59 UTC, outoftardis commented on MAINTAINERS.md
> +| William Richter       | [@WRRicht3r](https://github.com/WRRicht3r)           | ryan.rrr66@gmail.com            | Documentation                                                                 |
William, you, and I should be next to each other in the table, so that you can immediately see everyone working on the docs.

2022-11-21 07:59 UTC, outoftardis commented on MAINTAINERS.md
> +| Vasily Zyabkin        | [@BAStos525](https://github.com/BAStos525)           | zyabkin@soramitsu.co.jp         | DevOps                                                                        |
same as for doc maintainers: it makes more sense to list all developers next to each other, and others -- before or after

I'd also group them based on language where possible (at least those who only work on one sdk, e.g. java)

2022-11-21 10:07 UTC, WRRicht3r requested changes
Please address the comments by @outoftardis

2022-11-25 09:08 UTC, appetrosyan approved these changes

2022-11-25 09:09 UTC, merged