[documentation]: Update Iroha Client CLI readme
hyperledger/iroha pull request #3052
Opened 2023-01-10 08:59 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

2023-01-22 22:31 UTC, appetrosyan commented on client_cli/src/main.rs
> +    /// Get block stream from iroha peer
Excellent catch.

2023-01-22 22:31 UTC, appetrosyan commented on client_cli/README.md
> +You can execute multiple instructions with a single subcommand. Provide a JSON file with multiple instructions related to Iroha Client CLI to execute:
```suggestion
The reference implementation of the Rust client, `iroha_client_cli` is often used for diagnosing problems in other implementations. 

To test transactions in the JSON format (used in the genesis block and by other SDKs), pipe the transaction  into the client and add the `json` subcommand to the arguments: 
```

2023-01-22 22:31 UTC, appetrosyan commented on client_cli/README.md
> +### Execute Multiple Instructions
```suggestion
### Execute Multi-instruction Transactions
```

2023-01-22 22:31 UTC, appetrosyan commented on client_cli/README.md
> +| `peer`    | Execute commands related to p2p networking: registering and unregistering peers                                                             |
```suggestion
| `peer`    | Execute commands related to peer administration and networking                                                             |
```

2023-01-22 22:31 UTC, appetrosyan commented on client_cli/README.md
> +| `help`    | Print the help message for the tool or a subcommand                                                                                         |
```suggestion
| `help`    | Print the help message for `iroha_client_cli` and/or the current subcommand other than `help` subcommand                                                                                         |
```

2023-01-23 15:05 UTC, appetrosyan submitted a review, later dismissed

2023-01-23 15:09 UTC, WRRicht3r requested changes

2023-01-23 15:09 UTC, WRRicht3r commented on client_cli/README.md
> +| `blocks`  | Get block stream from Iorha peer                                                                                                            |
```suggestion
| `blocks`  | Get block stream from Iroha peer                                                                                                            |
```

2023-01-23 15:10 UTC, 6r1d submitted a review, later dismissed
LGTM

2023-01-23 15:16 UTC, appetrosyan approved these changes

2023-01-25 09:09 UTC, merged