[ci]: Switch from Codecov to Coveralls coverage
hyperledger/iroha pull request #3513
Opened 2023-05-22 09:30 UTC by BAStos525

## Description
Switch from `Codecov` to `Coveralls` coverage tool for iroha2-dev workflow.

### Linked issue
`Codecov` coverage tool doesn't show the correct percentage of code coverage between base and head branches during the  PR CI workflow job. This always shows a decrease in the code coverage value by some percentage.

### Benefits
Hopefully [`Coveralls` coverage tool](https://coveralls.io/repos) with help to solve the issue above.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [x] I replied to all comments after code review, marking all implemented changes with thumbs up

2023-05-22 15:04 UTC, appetrosyan approved these changes

2023-05-23 13:16 UTC, 6r1d requested changes

2023-05-23 13:16 UTC, 6r1d commented on .github/workflows/iroha2-dev-pr.yml
> +      - name: UUpload coverage to coveralls.io
I think it should be `Upload`, not `UUpload`.

2023-05-23 16:12 UTC, 6r1d approved these changes
Thanks for the update! LGTM.

2023-05-23 16:15 UTC, merged