[ci]: Update rustup toolchain & add musl-x86_64 component
hyperledger/iroha pull request #3650
Opened 2023-06-26 10:00 UTC by BAStos525

## Description
1. Add rustup toolchain `nightly-2023-06-25`.
2. Add [musl-x86_64](https://aur.archlinux.org/packages/musl-x86_64) Arch package. Probably should help to fix ` error occurred: Failed to find tool. Is `musl-g++` installed?` error.

### Linked issue
[Broken iroha2-dev compilation](https://github.com/hyperledger/iroha/actions/runs/5346333962/jobs/9693207108).

### Benefits
Should help to fix `registry` job in `I2::Dev::Publish` workflow.

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

2023-06-26 10:21 UTC, appetrosyan requested changes

2023-06-26 10:21 UTC, appetrosyan commented on Dockerfile.build
>  RUN rustup toolchain install nightly-2022-12-22-x86_64-unknown-linux-gnu
```suggestion
RUN rustup toolchain install nightly-2023-06-25-x86_64-unknown-linux-gnu
```

2023-06-26 10:21 UTC, appetrosyan commented on Dockerfile.build
> +RUN rustup toolchain add nightly-2023-06-25
```suggestion
```

2023-06-27 06:26 UTC, ilchu approved these changes

2023-06-27 09:54 UTC, appetrosyan approved these changes

2023-06-27 09:54 UTC, merged