[refactor] #3574: make all numeric values serialize as string literals
hyperledger/iroha pull request #3837
Opened 2023-08-25 09:30 UTC by DCNick3

## Description

This changes how numbers in expressions are serialized in json. 

`{"U32":  42}` -> `"42_u32"`
`{"U64":  42}` -> `"42_u64"`
`{"U128":  "42"}` -> `"42_u128"`
`42.0` -> `"42.0_fx"`

As a side-effect, this prohibits the usage of json number literals and, as such, no longer requires using serde_json's `arbitrary_precision` feature to deserialize 128-bit numbers.

This also removes some of the `#[serde(flatten)]`s from ISIs, as integers are no longer serialized as maps and can't be flattened.

This breaks the user-facing interface (AFAIK, only in `genesis.json`. Or is `client-cli` affected too?)

### Linked issue

Closes #3574 

### Benefits

- similar handing of all bit sizes, all numbers are quoted

2023-08-28 06:03 UTC, 0x009922 requested changes
LGTM. Could you add a test which serializes `42.0_fx`?

2023-08-28 08:45 UTC, 0x009922 submitted a review, later dismissed

2023-08-28 15:23 UTC, ilchu reviewed
Can approve after rebase as it has some pre-kura simplification remnants.

2023-08-29 08:36 UTC, 0x009922 approved these changes

2023-09-01 02:36 UTC, 0x009922 approved these changes

2023-09-01 20:59 UTC, pesterev approved these changes

2023-09-04 10:18 UTC, ilchu approved these changes

2023-09-04 10:24 UTC, 0x009922 approved these changes

2023-09-04 12:14 UTC, merged