[fix] #3995: Fix wasm cache directory permission bug in docker image
hyperledger/iroha pull request #3957
Opened 2023-10-04 21:21 UTC by Arjentix

## Description

Wasm cache directory is being created in the Dockerfile and all required permissions are being granted to the user.

### Linked issue

- Closes #3955 

### Benefits

Working Iroha stable image

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

2023-10-04 21:23 UTC, Arjentix commented
Due to a known problem I cannot fully build the image on my Mac M1, so I just trust myself. If anyone could test this, that would be cool.

Commands to test:

```bash
docker build . -t hyperledger/iroha2:stable
docker compose -f docker-compose.stable.yml up
```

2023-10-04 22:01 UTC, Arjentix commented
Btw, I have no idea why CI is failing. Seems like not my fault

2023-10-05 01:41 UTC, pesterev submitted a review, later dismissed
LGTM

2023-10-05 03:50 UTC, mversic commented
> Btw, I have no idea why CI is failing. Seems like not my fault

yeah, it's not your fault

2023-10-05 03:51 UTC, mversic approved these changes

2023-10-05 03:52 UTC, mversic requested changes
shouldn't you update Dockerfile.glibc as well?

2023-10-05 06:03 UTC, Arjentix commented
> shouldn't you update Dockerfile.glibc as well?

Oh, sure, I always forget

2023-10-05 06:21 UTC, mversic submitted a review, later dismissed

2023-10-05 06:48 UTC, AlexStroke requested changes

2023-10-05 06:48 UTC, AlexStroke commented on docker-compose.stable.yml
> +    platform: linux/amd64
We need `platform: linux/amd64` for each peer.

2023-10-05 08:15 UTC, mversic approved these changes

2023-10-05 08:20 UTC, AlexStroke approved these changes

2023-10-05 08:20 UTC, merged