[refactor] #3918: Rename validator to executor
hyperledger/iroha pull request #3976
Opened 2023-10-09 13:02 UTC by mversic

## Description

### Linked issue

Closes #{issue_number} 

### Benefits

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

2023-10-10 05:43 UTC, Erigara requested changes

2023-10-10 05:43 UTC, Erigara commented on docs/source/iroha_2_whitepaper.md
`Validator` here is used in different context.

2023-10-11 08:03 UTC, Erigara approved these changes

2023-10-11 13:27 UTC, ilchu submitted a review, later dismissed

2023-10-11 13:27 UTC, ilchu commented on core/src/smartcontracts/mod.rs
> +                // instruction, i.e. it will only be executed from the executor/executor.
```suggestion
                // instruction, i.e. it will only be executed from the executor.
```

2023-10-11 13:27 UTC, ilchu commented on core/src/smartcontracts/wasm.rs
> +    pub fn execute_executor_validate_transaction(
Maybe make it more readable like:
```suggestion
    pub fn execute_validate_transaction_in_executor(
```
And the same about all the functions with similar names in this module.

2023-10-11 13:27 UTC, ilchu commented on core/src/smartcontracts/wasm.rs
> +/// Useful because in *Executor* exist more entrypoints than just `migrate()` which is the
This sounds more correct to me:
```suggestion
/// Useful because *Executor* exposes more entrypoints than just `migrate()` which is the
```

2023-10-11 13:47 UTC, ilchu approved these changes

2023-10-11 13:47 UTC, ilchu approved these changes

2023-10-11 13:54 UTC, Erigara approved these changes

2023-10-11 13:56 UTC, merged