[fix] #4090 #3858: Fix having to pass IROHA_SKIP_WASM_CHECKS env variable with true
hyperledger/iroha pull request #4135
Opened 2023-12-11 06:38 UTC by Asem-Abdelhady

## Description

I deleted the need to pass the IROHA_SKIP_WASM_CHECKS while building with stable toolchain and added in CI

### Linked issue

Closes #4090 #3858

2023-12-11 06:50 UTC, mversic approved these changes

2023-12-11 09:26 UTC, 6r1d approved these changes

2023-12-11 09:31 UTC, mversic requested changes

2023-12-11 09:31 UTC, mversic commented on wasm_builder/src/lib.rs
> +    show_output: bool,
this shouldn't be a part of this PR

2023-12-12 07:55 UTC, mversic approved these changes

2023-12-12 07:58 UTC, 6r1d approved these changes

2023-12-12 08:18 UTC, merged