[chore]: #4231 Update MAINTAINERS
hyperledger/iroha pull request #4233
Opened 2024-01-24 12:49 UTC by 6r1d

Let's replace `iroha2-dev` MAINTAINERS file with a fresh version.

2024-01-24 12:52 UTC, outoftardis approved these changes

2024-01-24 12:56 UTC, WRRicht3r requested changes

2024-01-24 12:56 UTC, WRRicht3r commented on MAINTAINERS.md
>  Maintainers of Hyperledger Iroha project
```suggestion
Maintainers of the Hyperledger Iroha project
```

2024-01-24 12:56 UTC, WRRicht3r commented on MAINTAINERS.md
>  This is the list of maintainers, including their email address for direct communications:
```suggestion
This is the list of maintainers, including their email addresses for direct communication:
```

2024-01-24 12:56 UTC, WRRicht3r commented on MAINTAINERS.md
>  such as architecture, process, existing issues.
```suggestion
such as architecture, process, and existing issues.
```

2024-01-24 12:56 UTC, WRRicht3r commented on MAINTAINERS.md
> +| William Richter       | [@WRRicht3r](https://github.com/WRRicht3r)           | ryan.rrr66@gmail.com            | Documentation                                                                 |
```suggestion
| William Richter       | [@WRRicht3r](https://github.com/WRRicht3r)           | richter@soramitsu.co.jp            | Documentation                                                                 |
```

2024-01-24 13:04 UTC, mversic submitted a review, later dismissed

2024-01-24 13:53 UTC, mversic approved these changes

2024-01-24 19:55 UTC, Arjentix commented on MAINTAINERS.md
> +| Daniil Polyakov       | [@Arjentix](https://github.com/Arjentix)             | daniil.polyakov@soramitsu.co.jp | Development: Rust                                                             |
```suggestion
| Daniil Polyakov       | [@Arjentix](https://github.com/Arjentix)             | daniil.polyakov@soramitsu.co.jp | Development: Rust, C++                                                             |
```

As I can see we're adding additional languages here

2024-02-05 07:19 UTC, mversic approved these changes

2024-02-05 08:20 UTC, 0x009922 requested changes
I guess @s8sato should be mentioned too?

2024-02-05 08:31 UTC, 6r1d commented
Yes, most definitely.

2024-02-05 08:59 UTC, mversic approved these changes

2024-02-05 09:01 UTC, outoftardis approved these changes

2024-02-05 09:09 UTC, WRRicht3r approved these changes

2024-02-05 09:14 UTC, 0x009922 approved these changes

2024-02-05 10:40 UTC, merged