[documentation] #4234: Iroha 2 README YAC
hyperledger/iroha pull request #4235
Opened 2024-01-24 14:07 UTC by 6r1d

A one-liner solution for https://github.com/hyperledger/iroha/issues/4234

2024-01-24 14:15 UTC, WRRicht3r submitted a review, later dismissed

2024-01-24 14:16 UTC, outoftardis submitted a review, later dismissed

2024-01-24 14:18 UTC, yamkovoy reviewed
A small suggestion.

2024-01-24 14:18 UTC, yamkovoy commented on README.md
> +It is replaced with a new algorithm, [Sumeragi](https://iroha.tech/#sumeragi) in [Iroha 2](https://github.com/hyperledger/iroha/tree/iroha2-dev).
Iroha is _Crash Fault Tolerant_ and has its own consensus algorithm — [YAC](https://arxiv.org/pdf/1809.00554.pdf).
In Iroha 2, it is replaced with a new algorithm — [Sumeragi](https://iroha.tech/#sumeragi).

2024-01-24 14:22 UTC, yamkovoy requested changes
- Unified the wording.
- Replaced "-" with "—".

2024-01-24 14:22 UTC, yamkovoy commented on README.md
> +Iroha is _Crash Fault Tolerant_ and has its own consensus algorithm - [YAC](https://arxiv.org/pdf/1809.00554.pdf).
Iroha is _Crash Fault Tolerant_ and has its own consensus algorithm — [YAC](https://arxiv.org/pdf/1809.00554.pdf).
In Iroha 2, it is replaced with a new algorithm — [Sumeragi](https://iroha.tech/#sumeragi).

2024-01-24 14:34 UTC, yamkovoy requested changes

2024-01-24 14:34 UTC, yamkovoy commented on README.md
> +It is replaced with a new algorithm, [Sumeragi](https://iroha.tech/#sumeragi) in [Iroha 2](https://github.com/hyperledger/iroha/tree/iroha2-dev).
```suggestion
Iroha is _Crash Fault Tolerant_ and has its own consensus algorithm — [YAC](https://arxiv.org/pdf/1809.00554.pdf).
In Iroha 2, it is replaced with a new algorithm — [Sumeragi](https://iroha.tech/#sumeragi).
```

2024-01-24 21:08 UTC, yamkovoy approved these changes

2024-01-29 09:18 UTC, baziorek submitted a review, later dismissed

2024-04-29 07:35 UTC, merged