[poc] DO NOT MERGE: shared account ID is off curve
hyperledger/iroha pull request #4371
Opened 2024-03-18 07:33 UTC by s8sato

## Description

Proof of concept for the new account, with non-essential parts omitted. There is room for optimization in actual implementation.

### Linked issue

https://github.com/hyperledger/iroha/issues/2085#issuecomment-1985152267

### Benefits

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

2024-03-19 07:32 UTC, mversic requested changes

2024-03-19 07:32 UTC, mversic commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
haha, really suspicious

2024-03-19 07:32 UTC, mversic commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
can we, please, not include shared accounts in this PR?

2024-03-19 07:55 UTC, s8sato commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
This is not a PR, but how multi-signatory account holds its ID will soon become important.
Since this is still intended to be a compliant proposal to the discussion so far, could you be more specific about the issue or provide an alternative?

2024-03-19 11:39 UTC, s8sato commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
I guess you just advised not to preemptively implement shared accounts in the 1st PR. If so, we are on the same page

2024-03-20 23:26 UTC, 0x009922 commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
If so, this PoC should be entirely re-written? I see the code is mostly about shared accounts.

2024-03-21 05:40 UTC, s8sato commented on data_model/src/account.rs
> +    type RawId = [u8; 32];
No, this PoC is a part of the specification or discussion, and is completely different from the 1st PR.
So this is expected to be closed at some point

2024-07-10 04:52 UTC, s8sato commented
- Closed as this was for #4373, which has been resolved

2024-07-10 04:52 UTC, closed without merging