refactor(view_change): only send current and previous view change proof
hyperledger/iroha pull request #4929
Opened 2024-08-02 11:35 UTC by Erigara

## Description

Instead of sending every view change proof only view change proof for current round and previous verified proof are sent.

### Linked issue

Closes #4926 

### Benefits

This help peer which is lagging behind to directly jump to most recent view change and participate in consensus.

2024-08-21 19:10 UTC, SamHSmith approved these changes
Looks great.

2024-09-05 05:30 UTC, mversic requested changes

2024-09-05 05:30 UTC, mversic commented on core/src/sumeragi/main_loop.rs
>                      .unwrap_or_else(|err| error!("{err}"));
```suggestion
                    .expect("INTERNAL BUG: Invalid view change proof");
```

this can't fail, can it?

2024-09-05 06:01 UTC, mversic approved these changes

2024-09-05 13:21 UTC, merged