refactor: Change parameters format in genesis.json
hyperledger/iroha pull request #5020
Opened 2024-08-29 18:10 UTC by dima74

## Context

Fixes #4813

### Solution

Changes format of `genesis.json` from:

```json5
{
  ...
  "parameters": [
    {
      "Sumeragi": {
        "BlockTimeMs": 2000
      }
    },
    {
      "Sumeragi": {
        "CommitTimeMs": 4000
      }
    },
    ...
    {
      "Transaction": {
        "MaxInstructions": 4096
      }
    },
    ...
```

to:

```json5
{
  ...
  "parameters": {
    "sumeragi": {
      "block_time_ms": 2000,
      "commit_time_ms": 4000,
      ...
    },
    "transaction": {
      "max_instructions": 4096,
      ...
    },
    ...
```

### Migration Guide (optional)

* `kagami genesis generate` will generate genesis in the new format. Custom genesis generator tools should be changed to new format. 
* Note that schema.json has type entry `RawGenesisTransaction` corresponding to genesis.json file

### Review notes (optional)

### Checklist

- [ ] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.

2024-08-29 18:11 UTC, dima74 commented on docs/source/references/schema.json
> +        "type": "Option<Parameters>"
Here are changes to the schema (https://github.com/hyperledger/iroha/issues/4813#issuecomment-2316873814)

2024-08-30 08:21 UTC, mversic commented on data_model/src/parameter.rs
> +        pub fn default_fuel() -> NonZeroU64 {
```suggestion
        pub const fn default_fuel() -> NonZeroU64 {
```

can't it be `const fn`?

2024-08-30 08:22 UTC, mversic approved these changes

2024-08-31 08:50 UTC, mversic approved these changes

2024-08-31 08:52 UTC, mversic requested changes

2024-08-31 08:52 UTC, mversic commented on data_model/src/parameter.rs
> +        pub const fn default_transactions_in_block() -> NonZeroU64 {
```suggestion
        pub const fn transactions_in_block() -> NonZeroU64 {
```

2024-08-31 08:52 UTC, mversic commented on data_model/src/parameter.rs
> +        pub const fn default_transactions_in_block() -> NonZeroU64 {
it's in the module name

2024-08-31 08:56 UTC, mversic commented on data_model/src/parameter.rs
> +        pub const fn default_transactions_in_block() -> NonZeroU64 {
likewise elsewhere

2024-09-03 09:55 UTC, Erigara reviewed
No objections from codewise perspective and imo genesis this way looks more readable.

Let's see what SDK guys think: @Mingela @SamHSmith @0x009922

2024-09-04 03:26 UTC, mversic approved these changes

2024-09-04 03:47 UTC, mversic commented on defaults/genesis.json
> +      "memory": 55000000
```suggestion
      "memory": 55_000_000
```

I was just wondering if `json` supports underscore separator in a numeric literal? Would this even be possible to produce with `serde`?

2024-09-04 03:51 UTC, mversic commented on defaults/genesis.json
> +      "memory": 55000000
not supported by `serde

2024-09-09 06:06 UTC, Erigara approved these changes

2024-09-09 06:19 UTC, merged

2024-09-09 11:43 UTC, dima74 commented
@BAStos525 @timofeevmd format of parameters in genesis.json has changed. Please see PR description for details of the new format.