refactor: Use `ConstVec` for instructions in `Executable`
hyperledger/iroha pull request #5096
Opened 2024-09-23 14:37 UTC by dima74

## Context

Meta: #5083
Fixes #5092

### Solution

Use `Box<[InstructionBox]>` instead of `Vec` to ensure we don't waste any memory on a buffer. 
See https://github.com/hyperledger/iroha/issues/5083#issuecomment-2363844455, https://github.com/hyperledger/iroha/issues/5083#issuecomment-2364089885, and https://github.com/hyperledger/iroha/issues/5083#issuecomment-2364144603 for details

### Checklist

- [ ] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

2024-09-23 14:44 UTC, DCNick3 approved these changes

2024-09-23 23:02 UTC, mversic commented on crates/iroha_data_model/src/visit.rs
> +            for isi in instructions.as_ref() {
```suggestion
            for isi in &instructions {
```
we should rather implement `IntoIterator for &ConstVec`

2024-09-23 23:03 UTC, mversic commented on crates/iroha_data_model/src/transaction.rs
> +        Self::Instructions(iter.into_iter().map(Into::into).collect::<Vec<_>>().into())
```suggestion
        Self::Instructions(iter.into_iter().map(Into::into).collect())
```

can we implement `FromIterator for ConstVec`?

2024-09-23 23:03 UTC, mversic commented on crates/iroha_data_model/src/transaction.rs
> +        Self::Instructions(iter.into_iter().map(Into::into).collect::<Vec<_>>().into())
```suggestion
        Self::Instructions(iter.into_iter().map(Into::into).collect())
```

can we implement FromIterator for ConstVec?

2024-09-23 23:08 UTC, mversic requested changes

2024-09-23 23:08 UTC, mversic commented on crates/iroha_data_model/src/transaction.rs
> +        Self::Instructions(iter.into_iter().map(Into::into).collect::<Vec<_>>().into())
```suggestion
        Self::Instructions(iter.into_iter().map(Into::into).collect())
```

can we implement `FromIterator for ConstVec`?

2024-09-24 11:54 UTC, mversic approved these changes

2024-09-25 19:57 UTC, DCNick3 approved these changes

2024-09-26 00:36 UTC, merged