feat: Sort descending in `FindTransactions` query
hyperledger/iroha pull request #5190
Opened 2024-10-23 20:06 UTC by dima74

## Context

Fixes #4986

### Checklist

- [ ] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

2024-10-23 20:20 UTC, mversic requested changes

2024-10-23 22:07 UTC, 0x009922 approved these changes

2024-10-23 22:07 UTC, 0x009922 commented on crates/iroha/tests/tx_history.rs
> +                assert!(tx.creation_time() <= prev_creation_time);
This is an assertion in the test, so it's perfectly reasonable here imo.

2024-10-24 07:02 UTC, mversic commented on crates/iroha/tests/tx_history.rs
> +                assert!(tx.creation_time() <= prev_creation_time);
IMO it gives impression that some invariant is being maintained here. It's perfectly fine for network to reorder these transactions. There is no such guarantee given by Iroha that transaction will be ordered by creation time.

2024-10-24 07:02 UTC, mversic approved these changes

2024-10-24 07:03 UTC, mversic commented on crates/iroha/tests/tx_history.rs
> +                assert!(tx.creation_time() <= prev_creation_time);
anyways, this discussion can be resolved

2024-10-24 13:41 UTC, merged