build in docker
hyperledger/iroha pull request #776
Opened 2021-01-21 11:54 UTC by Alexey-N-Chernyshov

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>

### Description of the Change
Build moved to docker.
Add ACCOUNT_ID to client config.

### Benefits
Can build on different architectures.

### Possible Drawbacks 
Can be simplified with `cargo install --path .` if it is supported in build manifest.

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*
Alternative docker base can be used, not only Alpine linux.

2021-01-21 16:42 UTC, eadventurous approved these changes

2021-01-22 00:33 UTC, MizukiSonoko approved these changes

2021-01-22 08:04 UTC, humb1t requested changes

2021-01-22 08:04 UTC, humb1t commented on Dockerfile
>  CMD ["./iroha"]
If you make compilation part of the docker image, please make it multi stage so in the end we will work only with resulting binary and image needed to run it, not build it.
https://docs.docker.com/develop/develop-images/multistage-build/

2021-01-27 07:29 UTC, humb1t requested changes

2021-01-27 07:29 UTC, humb1t commented on Dockerfile
> +RUN cp target/release/iroha ..
Add a new `FROM` before (like [here](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds)) so build artifacts like `/target` folder won't go into our result image and use image without rust toolchain installed as a base.

2021-01-27 13:42 UTC, humb1t approved these changes

2021-01-27 13:48 UTC, merged