Set signature condition support in CLI
hyperledger/iroha pull request #807
Opened 2021-02-11 13:39 UTC by i1i1

Signature conditions are loaded from file with just an expression like this:
```json
{
	"Raw": {
		"Bool": true
	}
}
```

Signed-off-by: i1i1 <vanyarybin1@live.ru>

### Description of the Change

### Benefits

### Possible Drawbacks 

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*

2021-02-11 14:04 UTC, humb1t approved these changes

2021-02-11 14:41 UTC, eadventurous requested changes

2021-02-11 14:41 UTC, eadventurous commented on iroha_client_cli/src/main.rs
> +									.help("Account's public key as double-quoted string.")
```suggestion
									.help("A JSON file with Iroha Expression that represents signature condition")
```

2021-02-12 07:23 UTC, eadventurous approved these changes

2021-02-12 07:29 UTC, merged