add wsv restore mode - sync blockstore
hyperledger/iroha pull request #812
Opened 2021-02-15 09:58 UTC by Alexey-N-Chernyshov

add --drop_state param, param --reuse_state is default

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>

### Description of the Change

### Benefits

### Possible Drawbacks 

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*

2021-02-17 09:24 UTC, kamilsa approved these changes

2021-02-18 07:53 UTC, iceseer requested changes

2021-02-18 07:53 UTC, iceseer commented on irohad/ametsuchi/impl/flat_file/flat_file.cpp
> +    }
You don't need to clear this cache and iterate through the whole block store on each call. You know the size of cache and you expect the exact file with determined name.

2021-02-18 07:53 UTC, iceseer commented on irohad/ametsuchi/impl/flat_file/flat_file.cpp
>    return (available_blocks_.empty()) ? 0 : *available_blocks_.rbegin();
I expect this method to be constant and very light. To make multiple FS calls is not a good decision. This mode must be disconnectable. The best way I see is an option for FlatFile to skip write blocks. And independent mechanics, that scans the directory for new and not locked expected files, that can be read.

2021-02-18 07:53 UTC, iceseer commented on irohad/ametsuchi/impl/flat_file/flat_file.cpp
> +      available_blocks_.insert(*id);
We can't add this file for processing, until we are sure, that the file is released by other process.

2021-02-18 07:53 UTC, iceseer commented on irohad/ametsuchi/impl/wsv_restorer_impl.cpp
> +        while (wait_for_new_blocks) {
There is no ```res``` check.

2021-02-24 08:14 UTC, iceseer approved these changes

2021-02-25 12:59 UTC, merged