Replace timestamp with typesafe wrapper
hyperledger/iroha pull request #819
Opened 2021-02-20 16:10 UTC by i1i1

Signed-off-by: i1i1 <vanyarybin1@live.ru>

### Description of the Change

### Benefits

### Possible Drawbacks 

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*

2021-02-22 11:45 UTC, humb1t reviewed
Why can't we use DateTime directly?

2021-02-22 15:37 UTC, eadventurous requested changes

2021-02-22 15:37 UTC, eadventurous commented on iroha_data_model/src/query.rs
> -        }
I think the timestamp that we had here is okay, as it is a unix timestamp and therefore it is universal. We just don't want to convert it to string. Use u64 as in `creation_time` in transaction.

2021-02-22 15:37 UTC, eadventurous commented on iroha_data_model/src/query.rs
> -        }
Maybe we can use scale's `CompactEncoding` for this, but I am not sure on this.

2021-02-24 08:09 UTC, eadventurous requested changes

2021-02-24 08:09 UTC, eadventurous commented on iroha_data_model/src/query.rs
> +        payload.extend_from_slice(&self.timestamp_ms.0.to_le_bytes());
We have a rule in our style guide not to access inner elements by position index, please destructure it instead.

2021-02-24 08:09 UTC, eadventurous commented on iroha_data_model/src/query.rs
> +    pub timestamp_ms: Compact<u128>,
Can we use `#[codec(compact)]` attribute here instead?

2021-02-24 08:09 UTC, eadventurous commented on iroha_data_model/src/query.rs
> +    pub timestamp_ms: Compact<u128>,
This way it will be easier to use `QueryRequest.timestamp_ms` in code.

2021-02-24 08:38 UTC, eadventurous approved these changes

2021-02-24 09:03 UTC, merged