Add versioning of blocks
hyperledger/iroha pull request #857
Opened 2021-03-15 09:33 UTC by i1i1

Signed-off-by: i1i1 <vanyarybin1@live.ru>

### Description of the Change

### Benefits

### Possible Drawbacks 

### Usage Examples or Tests *[optional]*

### Alternate Designs *[optional]*

2021-03-15 11:14 UTC, eadventurous reviewed
We also need to use `VersionedValidBlock` in sumeragi consensus. So that peers can be updated without the whole network being stopped.

2021-03-15 11:15 UTC, eadventurous commented
Do you want to add these functionality in this or in a separate PR?

2021-03-15 11:16 UTC, i1i1 commented
Yeah, almost forgot about it. Will be in this pr soon!

2021-03-15 11:23 UTC, humb1t requested changes

2021-03-15 11:23 UTC, humb1t commented on iroha/src/kura.rs
> +    async fn read_all(&self) -> Result<Vec<ValidBlock>> {
Seems like `read` and `read_all` should both return one of these block's types: `VersionedValidBlock` or `ValidBlock`

2021-03-15 12:42 UTC, takemiyamakoto approved these changes

2021-03-15 13:29 UTC, humb1t approved these changes

2021-03-16 14:35 UTC, takemiyamakoto approved these changes

2021-03-17 12:05 UTC, eadventurous commented on iroha/src/block_sync.rs
> +                        );
Maybe it should be `warn`?

2021-03-17 12:05 UTC, eadventurous commented on iroha/src/block_sync.rs
> +                        ),
Also should be `warn` to my mind, also please change the error message. Here the message should be that there are no blocks after `hash`.

2021-03-17 12:10 UTC, eadventurous requested changes

2021-03-17 12:10 UTC, eadventurous commented on iroha/src/queue.rs
> +    pub fn push_pending_transaction(&mut self, tx: VersionedAcceptedTransaction) -> Result<()> {
Please move queue simplification into a separate PR.

2021-03-17 12:10 UTC, eadventurous commented on iroha_version/iroha_version_derive/tests/json.rs
> -        let raw_string = "{\"version\":\"3\",\"content\":\"test string\"}";
It is important to compare raw content for the test.

2021-03-17 12:10 UTC, eadventurous commented on iroha_version/iroha_version_derive/tests/json.rs
> -        let raw_string = "{\"version\":\"3\",\"content\":\"test string\"}";
This should not be removed.

2021-03-17 12:10 UTC, eadventurous commented on iroha_version/iroha_version_derive/tests/scale.rs
> -        let raw_string = "test string".encode();
Also here

2021-03-18 08:43 UTC, eadventurous approved these changes

2021-03-18 08:43 UTC, merged