881 no --drop-state flag for first run
hyperledger/iroha pull request #900
Opened 2021-03-25 16:22 UTC by kuvaldini

Anyway database initialization required:
```
initdb ~/iroha/noda3_db/
postgres -D ~/iroha/noda3_db/ -d1 -p5432 &
createuser -s iroha_user -p5432
```

2021-03-26 10:06 UTC, iceseer requested changes

2021-03-26 10:06 UTC, iceseer commented on irohad/subscription/subscription_manager.hpp
> +
Will add in additional PR.

2021-03-26 10:20 UTC, kuvaldini commented on irohad/main/impl/pg_connection_init.cpp
> +    int work_db_exists;
It should be bool but soci does not accept bool. int works as logical boolean here

2021-03-27 11:39 UTC, kamilsa approved these changes

2021-03-31 09:19 UTC, kuvaldini commented on irohad/subscription/subscription_manager.hpp
> +
removed.

2021-03-31 10:38 UTC, iceseer approved these changes

2021-03-31 11:29 UTC, merged

2021-03-31 13:30 UTC, lebdron commented
@iceseer @kuvaldini did you check that tests don't pass?

2021-03-31 13:31 UTC, kuvaldini commented
Оо нет